<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="22034" started-at="2016-04-01T07:46:23Z" finished-at="2016-04-01T07:46:45Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="22034" started-at="2016-04-01T07:46:23Z" finished-at="2016-04-01T07:46:45Z">
      <class name="com.softserve.edu.rs.tests.SmokeAppSuiteTest2">
        <test-method status="PASS" signature="oneTimeSetUp()[pri:0, instance:com.softserve.edu.rs.tests.SmokeAppSuiteTest2@282ba1e]" name="oneTimeSetUp" is-config="true" duration-ms="8" started-at="2016-04-01T10:46:23Z" finished-at="2016-04-01T10:46:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- oneTimeSetUp -->
        <test-method status="FAIL" signature="adminLogin1(com.softserve.edu.rs.pages.Application2, com.softserve.edu.rs.data.users.IUser)[pri:0, instance:com.softserve.edu.rs.tests.SmokeAppSuiteTest2@282ba1e]" name="adminLogin1" duration-ms="22005" started-at="2016-04-01T10:46:23Z" data-provider="adminUsers" finished-at="2016-04-01T10:46:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.softserve.edu.rs.pages.Application2@13969fbe]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[com.softserve.edu.rs.data.users.User@6aaa5eb0]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [Вихiд] but found [Вихід]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [Вихiд] but found [Вихід]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.softserve.edu.rs.tests.SmokeAppSuiteTest2.adminLogin1(SmokeAppSuiteTest2.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- adminLogin1 -->
      </class> <!-- com.softserve.edu.rs.tests.SmokeAppSuiteTest2 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
